apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
  namespace: project
data:
  mongodb_url: mongodb-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  labels:
    app: spring-app
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
      namespace: project
    spec:
      containers:
      - name: spring-container
        image: amruth0005/spring-boot-mongo-kube
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: spring-config
              key: mongodb_url
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username_mongo
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password_mongo


---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  labels:
    app: spring-app
  namespace: project
spec:
  selector:
    app: spring-app
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: project
type: Opaque
data:
   username_mongo: dXNlcm5hbWU=
   password_mongo: cGFzc3dvcmQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
      namespace: project
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username_mongo
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password_mongo
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
  namespace: project
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP

