apiVersion: apps/v1
kind: Deployment
metadata:
  name: springriplicationiset
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      name: springpod
      labels:
        app: spring
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: springcontainer
        image: 172.31.9.197:8083/spring-boot-app:17
        ports:
        - containerPort: 8080
        env:
          - name: MONGO_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: secretspringmongo
                key: username
          - name: MONGO_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secretspringmongo
                key: passcode
          - name: MONGO_DB_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: springmongoconfig 
                key: mongodb_url
                            
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: spring
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
