apiVersion: v1
kind: Secret
metadata:
   name: springmongosecret
type: Opaque
data:
  username: dXNlcm5hbWU=
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
   name: springmongoconfig
data:
  mongodb_url: mongoservice
